name: CD Pipeline

on:
  push:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/dbt-labs/dbt-postgres:1.6.3
    env:
      POSTGRES_HOST: ${{ vars.POSTGRES_HOST }}
      POSTGRES_USER: ${{ vars.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      POSTGRES_DB: ${{ vars.POSTGRES_DB }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          dbt deps
      - name: Run unit tests
        run: |
          dbt test --target test --select tag:unit-test
      - name: Run component tests
        run: |
          dbt test --target test --select tag:unit-test
  deploy-preview:
    name: Deploy to test environment
    needs: [test]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    container:
      image: ghcr.io/dbt-labs/dbt-postgres:1.6.3
    env:
      POSTGRES_HOST: ${{ vars.POSTGRES_HOST }}
      POSTGRES_USER: ${{ vars.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      POSTGRES_DB: ${{ vars.POSTGRES_DB }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run seeds
        run: |
          dbt seed --target test
      - name: Run source contract tests
        run: |
          dbt test --target test --select tag:contract-test-source
      - name: Run data transformations
        run: |
          dbt run --target test
