name: Deploy

on:
  workflow_call:
    inputs:
      environment-name:
        required: true
        type: string

env:
  POSTGRES_HOST: ${{ vars.POSTGRES_HOST }}
  POSTGRES_USER: ${{ vars.POSTGRES_USER }}
  POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
  POSTGRES_DB: ${{ vars.POSTGRES_DB }}

jobs:
  seed-source-tables:
    name: Seed source tables
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment-name }}
    container:
      image: ghcr.io/dbt-labs/dbt-postgres:1.6.3
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          dbt deps
      - name: Run seeds
        run: |
          dbt seed --target ${{ inputs.environment-name }}
  source-contract-tests:
    name: Run source contract tests
    needs: [seed-source-tables]
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment-name }}
    container:
      image: ghcr.io/dbt-labs/dbt-postgres:1.6.3
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          dbt deps
      - name: Run seeds
        run: |
          dbt seed --target ${{ inputs.environment-name }}\
      - name: Run source contract tests
        run: |
          dbt test --target ${{ inputs.environment-name }} --select tag:contract-test-source
  deploy:
    name: Deploy
    needs: [source-contract-tests]
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment-name }}
    container:
      image: ghcr.io/dbt-labs/dbt-postgres:1.6.3
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          dbt deps
      - name: Run data transformations
        run: |
          dbt run --target ${{ inputs.environment-name }}

  generate-observability-report:
    name: Generate observability report
    # needs: [deploy]
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment-name }}
    container:
      image: ghcr.io/dbt-labs/dbt-postgres:1.6.3
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run Elementary
        uses: elementary-data/run-elementary-action@v1.12
        with:
          warehouse-type: postgres
          edr-command: edr report --target-path "report/" --file-path "report/index.html"
      - name: Upload report
        uses: actions/upload-artifact@v3
        with:
          name: report.html
          path: ./report/index.html
      - name: Deploy report
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./report
